// GET
export const GET_NEW_RELEASE = 'GET_NEW_RELEASE';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_FEATURED_PLAYLIST = 'GET_FEATURED_PLAYLIST';

// SET
export const SET_NEW_RELEASE = 'SET_NEW_RELEASE';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_FEATURED_PLAYLIST = 'SET_FEATURED_PLAYLIST';
export const SET_LOADING_NEW_RELEASE = 'SET_LOADING_NEW_RELEASE';
export const SET_LOADING_FEATURED_PLAYLIST = 'SET_LOADING_FEATURED_PLAYLIST';
export const SET_LOADING_CATEGORIES = 'SET_LOADING_CATEGORIES';
